// 一次性 prefill runner(原 zllm-bench qnn_htp_cached_prefill):用缓存分段图
// 建立 KV 与首 token 状态,供 decode runner 恢复。层数与 trace 元数据 id 由
// 配置注入(默认 2B 布局)。由 zllm-qnn-prefill bin 经 C ABI 调用。
#include "htp_graph.hpp"
#include "htp_session.hpp"
#include <sys/stat.h>
#include <unistd.h>

extern "C" int zllm_qnn_prefill_main(int argc,char**argv){try{
 if(argc!=3||std::string(argv[1])!="--config")return 2;std::ifstream cf(argv[2]);json cfg;cf>>cfg;std::string root=cfg.at("root"),cache_dir=cfg.at("context_cache_dir");auto tokens=cfg.at("prompt_tokens").get<std::vector<unsigned>>();unsigned capacity=cfg.value("prompt_capacity",64u);if(tokens.empty()||tokens.size()>capacity)throw std::runtime_error("prompt token 数量越界");float margin=cfg.value("range_margin",1.1f);
 auto session=htp_session_open(cfg,true);
 auto&api=session.api;auto&system=session.system;Qnn_BackendHandle_t backend=session.backend;Qnn_DeviceHandle_t device=session.device;
 std::map<int,json>meta;std::ifstream tf(root+"/trace.jsonl");std::string line;while(std::getline(tf,line)){auto j=json::parse(line);if(j.contains("id"))meta[j["id"].get<int>()]=j;}auto step=[&](int id){return std::max(meta.at(id)["max"].get<float>()*margin/32767,1e-8f);};
 auto begin=std::chrono::steady_clock::now();unsigned hidden_cols=meta.at(0)["cols"],kv_cols=meta.at(7)["kv_heads"].get<unsigned>()*meta.at(7)["dim"].get<unsigned>();Value hidden{std::vector<uint16_t>((size_t)capacity*hidden_cols),capacity,hidden_cols,step(0)};
 {std::ifstream mf(root+"/embedding.json");json spec;mf>>spec;unsigned block=spec["block_rows"];std::ifstream data(root+"/embedding.u16",std::ios::binary),steps(root+"/embedding.steps",std::ios::binary);std::deque<Value>tables;Graph graph(api,backend,device);std::vector<Qnn_Tensor_t>rows;for(unsigned row=0;row<capacity;row++){unsigned token=row<tokens.size()?tokens[row]:0,group=token/block;float source_step;steps.clear();steps.seekg(group*4);steps.read((char*)&source_step,4);tables.push_back(Value{std::vector<uint16_t>((size_t)block*hidden_cols),block,hidden_cols,source_step});data.clear();data.seekg((uint64_t)group*block*hidden_cols*2);data.read((char*)tables.back().data.data(),tables.back().data.size()*2);auto selected=graph.slice(graph.input(tables.back()),token%block,1,0),converted=graph.tensor({1,hidden_cols},hidden.step);graph.op(QNN_OP_CONVERT,{selected},converted);rows.push_back(converted);}graph.op(QNN_OP_CONCAT,rows,graph.output(hidden),{graph.scalar("axis",0)});graph.execute();}
 unsigned layers=cfg.value("model_layers",42u);json state={{"prompt_tokens",tokens.size()},{"layers",layers}};std::string state_dir=cfg.at("state_out_dir");mkdir(state_dir.c_str(),0755);
 for(unsigned layer=0;layer<layers;layer++){
  int last=15*(layer+1),b=1+15*layer;auto bytes=read<uint8_t>(cache_dir+"/segment_"+std::to_string(last)+".bin");QnnSystemContext_Handle_t system_context=nullptr;check(system.systemContextCreate(&system_context),"system context");const QnnSystemContext_BinaryInfo_t*binary_info=nullptr;Qnn_ContextBinarySize_t info_size=0;check(system.systemContextGetBinaryInfo(system_context,bytes.data(),bytes.size(),&binary_info,&info_size),"binary info");auto info=graph_info(binary_info);if(info.input_count!=1||info.output_count!=3)throw std::runtime_error("prefill cache 输入输出数量不匹配 layer="+std::to_string(layer)+" inputs="+std::to_string(info.input_count)+" outputs="+std::to_string(info.output_count));Qnn_ContextHandle_t context=nullptr;Qnn_GraphHandle_t graph=nullptr;check(api.contextCreateFromBinary(backend,device,nullptr,bytes.data(),bytes.size(),&context,nullptr),"load context");check(api.graphRetrieve(context,info.name,&graph),"retrieve graph");Value key{std::vector<uint16_t>((size_t)capacity*kv_cols),capacity,kv_cols,step(b+5)},value{std::vector<uint16_t>((size_t)capacity*kv_cols),capacity,kv_cols,step(b+3)},next{std::vector<uint16_t>((size_t)capacity*hidden_cols),capacity,hidden_cols,step(b+14)};Qnn_Tensor_t input=info.inputs[0],outputs[3]={info.outputs[0],info.outputs[1],info.outputs[2]};input.v1.clientBuf={hidden.data.data(),(uint32_t)hidden.data.size()*2};outputs[0].v1.clientBuf={key.data.data(),(uint32_t)key.data.size()*2};outputs[1].v1.clientBuf={value.data.data(),(uint32_t)value.data.size()*2};outputs[2].v1.clientBuf={next.data.data(),(uint32_t)next.data.size()*2};check(api.graphExecute(graph,&input,1,outputs,3,nullptr,nullptr),"cached prefill execute");write(state_dir+"/k"+std::to_string(layer)+".u16",key.data);write(state_dir+"/v"+std::to_string(layer)+".u16",value.data);state["kv"][std::to_string(layer)]={{"rows",tokens.size()},{"cols",kv_cols},{"key_step",key.step},{"value_step",value.step}};hidden=std::move(next);api.contextFree(context,nullptr);system.systemContextFree(system_context);
 }
 unsigned vocab=meta.at(633)["cols"].get<unsigned>();Value last_hidden{std::vector<uint16_t>(hidden_cols),1,hidden_cols,hidden.step};std::copy_n(hidden.data.begin()+(tokens.size()-1)*hidden_cols,hidden_cols,last_hidden.data.begin());int fn=632,head_id=633;Value logits{std::vector<uint16_t>(vocab),1,vocab,step(head_id)};std::string head_cache=cache_dir+"/prefill_head.bin";
 if(access(head_cache.c_str(),R_OK)==0){auto bytes=read<uint8_t>(head_cache);QnnSystemContext_Handle_t system_context=nullptr;check(system.systemContextCreate(&system_context),"head system context");const QnnSystemContext_BinaryInfo_t*binary_info=nullptr;Qnn_ContextBinarySize_t info_size=0;check(system.systemContextGetBinaryInfo(system_context,bytes.data(),bytes.size(),&binary_info,&info_size),"head binary info");auto info=graph_info(binary_info);if(info.input_count!=1||info.output_count!=1)throw std::runtime_error("head cache 输入输出数量不匹配");Qnn_ContextHandle_t context=nullptr;Qnn_GraphHandle_t graph=nullptr;check(api.contextCreateFromBinary(backend,device,nullptr,bytes.data(),bytes.size(),&context,nullptr),"load head context");check(api.graphRetrieve(context,info.name,&graph),"retrieve head graph");Qnn_Tensor_t input=info.inputs[0],output=info.outputs[0];input.v1.clientBuf={last_hidden.data.data(),(uint32_t)last_hidden.data.size()*2};output.v1.clientBuf={logits.data.data(),(uint32_t)logits.data.size()*2};check(api.graphExecute(graph,&input,1,&output,1,nullptr,nullptr),"cached head execute");api.contextFree(context,nullptr);system.systemContextFree(system_context);}else{Graph graph(api,backend,device);auto input=graph.input(last_hidden);auto&j=meta.at(fn);auto epsilon=graph.constant({std::sqrt(hidden_cols*j["eps"].get<float>())},{1,1},last_hidden.step),eps_same=graph.tensor({1,1},last_hidden.step);graph.op(QNN_OP_CONVERT,{epsilon},eps_same);auto padded=graph.tensor({1,hidden_cols+1},last_hidden.step);graph.op(QNN_OP_CONCAT,{input,eps_same},padded,{graph.scalar("axis",1)});auto unit=graph.tensor({1,hidden_cols+1},j["normalized_step"].get<float>()/std::sqrt((float)hidden_cols));auto eps=graph.scalar("epsilon",0,QNN_DATATYPE_FLOAT_32);eps.scalarParam.floatValue=1e-12f;graph.op(QNN_OP_L2_NORM,{padded},unit,{graph.scalar("axis",1),eps});auto normalized=graph.slice(unit,0,hidden_cols);auto nw=read<float>(root+"/w378.f32");for(auto&v:nw)v=(v+j["offset"].get<float>())*std::sqrt((float)hidden_cols);auto normed=graph.tensor({1,hidden_cols},step(fn));graph.op(QNN_OP_ELEMENT_WISE_MULTIPLY,{normalized,graph.constant(nw,{1,hidden_cols})},normed);auto codes=read<uint8_t>(root+"/w379.pc4awq");auto scales=read<float>(root+"/w379.pc4awqscales");graph.buffers.push_back(std::move(codes));auto weight=graph.lowbit({hidden_cols,logits.cols},graph.buffers.back().data(),graph.buffers.back().size(),std::move(scales),4);graph.op(QNN_OP_MAT_MUL,{normed,weight},graph.output(logits));graph.save(head_cache);graph.execute();}
 uint32_t token=argmax(logits);state["first_token"]=token;std::string state_path=state_dir+"/state.json",temporary_path=state_path+".tmp";{std::ofstream file(temporary_path);file<<state.dump();file.close();if(!file)throw std::runtime_error("写入 prefill state 失败");}if(std::rename(temporary_path.c_str(),state_path.c_str()))throw std::runtime_error("发布 prefill state 失败");double ms=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-begin).count();printf("PREFILL tokens=%zu wall_ms=%.3f tok_s=%.3f\n",tokens.size(),ms,1000.0*tokens.size()/ms);printf("TOKEN position=%zu actual=%u\n",tokens.size(),token);return 0;
}catch(std::exception&e){fprintf(stderr,"ERROR: %s\n",e.what());return 2;}}
