//! Kimi-K3 模型架构配置。

#[derive(Debug)]
pub struct KimiK3VisionConfig {
    pub hidden_size: usize,
    pub layer_count: usize,
    pub num_heads: usize,
    pub qkv_hidden_size: usize,
    pub intermediate_size: usize,
    pub patch_size: usize,
    pub merge_kernel_size: [usize; 2],
    pub projection_dim: usize,
    pub norm_eps: f32,
}

#[derive(Debug)]
pub struct KimiK3Config {
    pub vocab_size: usize,
    pub hidden_size: usize,
    pub layer_count: usize,
    pub dense_layer_count: usize,
    pub max_position_embeddings: usize,
    pub attn_res_block_size: usize,
    pub num_attention_heads: usize,
    pub full_attention_layers: Vec<usize>,
    pub kda_head_dim: usize,
    pub kda_short_conv_kernel_size: usize,
    pub kda_use_full_rank_gate: bool,
    pub kda_gate_lower_bound: f32,
    pub q_lora_rank: usize,
    pub kv_lora_rank: usize,
    pub qk_nope_head_dim: usize,
    pub qk_rope_head_dim: usize,
    pub value_head_dim: usize,
    pub rope_theta: f32,
    pub dense_intermediate_size: usize,
    pub expert_intermediate_size: usize,
    pub routed_expert_hidden_size: usize,
    pub num_experts: usize,
    pub num_experts_per_token: usize,
    pub num_shared_experts: usize,
    pub routed_scaling_factor: f32,
    pub situ_beta: f32,
    pub situ_linear_beta: f32,
    pub rms_eps: f32,
    pub bos_token_id: u32,
    pub eos_token_ids: Vec<u32>,
    pub pad_token_id: u32,
    pub media_placeholder_token_id: u32,
    pub vision: KimiK3VisionConfig,
}

impl KimiK3Config {
    pub fn standard() -> Self {
        Self {
            vocab_size: 163_840,
            hidden_size: 7_168,
            layer_count: 93,
            dense_layer_count: 1,
            max_position_embeddings: 1_048_576,
            attn_res_block_size: 12,
            num_attention_heads: 96,
            full_attention_layers: (1..=23).map(|index| index * 4).chain([93]).collect(),
            kda_head_dim: 128,
            kda_short_conv_kernel_size: 4,
            kda_use_full_rank_gate: true,
            kda_gate_lower_bound: -5.0,
            q_lora_rank: 1_536,
            kv_lora_rank: 512,
            qk_nope_head_dim: 128,
            qk_rope_head_dim: 64,
            value_head_dim: 128,
            rope_theta: 10_000.0,
            dense_intermediate_size: 33_792,
            expert_intermediate_size: 3_072,
            routed_expert_hidden_size: 3_584,
            num_experts: 896,
            num_experts_per_token: 16,
            num_shared_experts: 2,
            routed_scaling_factor: 1.0,
            situ_beta: 4.0,
            situ_linear_beta: 25.0,
            rms_eps: 1.0e-5,
            bos_token_id: 163_584,
            eos_token_ids: vec![163_586],
            pad_token_id: 163_839,
            media_placeholder_token_id: 163_605,
            vision: KimiK3VisionConfig { hidden_size: 1_024, layer_count: 27, num_heads: 12, qkv_hidden_size: 1_536, intermediate_size: 4_096, patch_size: 14, merge_kernel_size: [2, 2], projection_dim: 7_168, norm_eps: 1.0e-5 },
        }
    }
}
